//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 12:05:40 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://beans.stage.com")
package com.stage.beans;
